/**
 * Business registry: 250+ niches → template category (queue/booking engine).
 * Data file is generated by: node scripts/build-business-registry.mjs
 */
import type { BusinessCategory } from '../store/AppContext';

/** When a profile has no nicheId, map template → primary industry group (customer filters). */
export const PRIMARY_INDUSTRY_GROUP: Record<BusinessCategory, string> = {
  men_salon: 'beauty',
  beauty_parlour: 'beauty',
  unisex_salon: 'beauty',
  clinic: 'healthcare',
  hospital: 'healthcare',
  restaurant: 'food',
  cafe: 'food',
  gym: 'fitness',
  spa: 'beauty',
  pet_care: 'healthcare',
  coaching: 'education',
  law_firm: 'services',
  photography: 'creative',
  repair_shop: 'repairs',
  laundry: 'repairs',
  event_planner: 'other',
  other: 'other',
};
import {
  ALL_BUSINESS_NICHE_ROWS,
  BUSINESS_REGISTRY_GROUPS,
  type BusinessNicheRow,
  type BusinessRegistryGroup,
} from './businessRegistry.data';

export type { BusinessNicheRow, BusinessRegistryGroup };

export { ALL_BUSINESS_NICHE_ROWS, BUSINESS_REGISTRY_GROUPS };

const byId = new Map<string, BusinessNicheRow>(
  ALL_BUSINESS_NICHE_ROWS.map((r) => [r.id, r])
);

export function getBusinessNicheById(id: string | null | undefined): BusinessNicheRow | undefined {
  if (!id) return undefined;
  return byId.get(id);
}

export function searchBusinessNiches(query: string): BusinessNicheRow[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_BUSINESS_NICHE_ROWS;
  return ALL_BUSINESS_NICHE_ROWS.filter(
    (r) =>
      r.label.toLowerCase().includes(q) ||
      r.labelHi.includes(query) ||
      r.id.toLowerCase().includes(q)
  );
}

export function getNichesForGroup(groupId: string): BusinessNicheRow[] {
  return ALL_BUSINESS_NICHE_ROWS.filter((r) => r.groupId === groupId);
}

/** Resolve Firestore industry section for filters (niche wins; else template fallback). */
export function getIndustryGroupIdForBusiness(
  businessType: BusinessCategory,
  nicheId?: string | null
): string {
  if (nicheId) {
    const n = getBusinessNicheById(nicheId);
    if (n) return n.groupId;
  }
  return PRIMARY_INDUSTRY_GROUP[businessType] || 'digital';
}

/** Visual hint per template — maps to CSS / Framer variants (extend over time). */
export type IndustryVisualStyle =
  | 'glass-neon'
  | 'glass-warm'
  | 'glass-clinical'
  | 'glass-luxury'
  | 'mesh-aurora'
  | 'clay-soft'
  | 'neo-brutal'
  | 'minimal-pro';

export function getVisualStyleForTemplate(t: BusinessCategory): IndustryVisualStyle {
  switch (t) {
    case 'men_salon':
    case 'unisex_salon':
      return 'glass-neon';
    case 'beauty_parlour':
      return 'glass-luxury';
    case 'restaurant':
    case 'cafe':
      return 'glass-warm';
    case 'clinic':
    case 'hospital':
      return 'glass-clinical';
    case 'gym':
      return 'neo-brutal';
    case 'spa':
      return 'mesh-aurora';
    case 'law_firm':
      return 'minimal-pro';
    case 'photography':
      return 'minimal-pro';
    case 'event_planner':
      return 'glass-luxury';
    default:
      return 'mesh-aurora';
  }
}
