import { BusinessCategory } from '../store/AppContext';

export interface CategoryTheme {
  /** Primary gradient from-to colors for headers */
  gradient: string;
  /** Background radial gradient */
  bgGradient: string;
  /** Primary accent color class (e.g. 'blue-400') */
  accent: string;
  /** Hex code for dynamic styles (e.g. '#3B82F6') */
  accentColor: string;
  /** Lighter accent for borders/badges */
  accentLight: string;
  /** Button/CTA color */
  btnBg: string;
  btnText: string;
  /** Status card gradient */
  statusOpen: string;
  /** Unique greeting for this business type */
  greeting: string;
  /** What is the owner called */
  ownerTitle: string;
  /** Dashboard title */
  dashTitle: string;
  /** Queue or booking terminology */
  queueLabel: string;
  /** Action button label */
  actionLabel: string;
  /** Design archetype for layout variations */
  archetype: 'beauty' | 'medical' | 'food' | 'professional';
}

export const CATEGORY_THEMES: Record<BusinessCategory, CategoryTheme> = {
  men_salon: {
    gradient: 'from-blue-600 to-indigo-700',
    bgGradient: 'from-blue-900/40 via-background to-background',
    accent: 'text-blue-400',
    accentColor: '#60A5FA',
    accentLight: 'border-blue-500/30 bg-blue-500/10',
    btnBg: 'bg-blue-600',
    btnText: 'text-white',
    statusOpen: 'from-blue-500/20 to-indigo-500/10 border-blue-500/30',
    greeting: '💈 Welcome, Boss!',
    ownerTitle: 'Barber',
    dashTitle: 'Salon Command Center',
    queueLabel: 'Queue',
    actionLabel: 'Next Customer →',
    archetype: 'beauty',
  },
  beauty_parlour: {
    gradient: 'from-pink-500 to-fuchsia-600',
    bgGradient: 'from-pink-900/40 via-background to-background',
    accent: 'text-pink-400',
    accentColor: '#F472B6',
    accentLight: 'border-pink-500/30 bg-pink-500/10',
    btnBg: 'bg-pink-600',
    btnText: 'text-white',
    statusOpen: 'from-pink-500/20 to-fuchsia-500/10 border-pink-500/30',
    greeting: '💅 Welcome, Gorgeous!',
    ownerTitle: 'Stylist',
    dashTitle: 'Beauty Studio',
    queueLabel: 'Clients',
    actionLabel: 'Next Client →',
    archetype: 'beauty',
  },
  unisex_salon: {
    gradient: 'from-violet-500 to-purple-700',
    bgGradient: 'from-violet-900/40 via-background to-background',
    accent: 'text-violet-400',
    accentColor: '#A78BFA',
    accentLight: 'border-violet-500/30 bg-violet-500/10',
    btnBg: 'bg-violet-600',
    btnText: 'text-white',
    statusOpen: 'from-violet-500/20 to-purple-500/10 border-violet-500/30',
    greeting: '✂️ Welcome Back!',
    ownerTitle: 'Stylist',
    dashTitle: 'Style Studio',
    queueLabel: 'Queue',
    actionLabel: 'Next Client →',
    archetype: 'beauty',
  },
  clinic: {
    gradient: 'from-teal-500 to-cyan-600',
    bgGradient: 'from-teal-900/40 via-background to-background',
    accent: 'text-teal-400',
    accentColor: '#2DD4BF',
    accentLight: 'border-teal-500/30 bg-teal-500/10',
    btnBg: 'bg-teal-600',
    btnText: 'text-white',
    statusOpen: 'from-teal-500/20 to-cyan-500/10 border-teal-500/30',
    greeting: '🩺 Welcome, Doctor!',
    ownerTitle: 'Doctor',
    dashTitle: 'Clinic Dashboard',
    queueLabel: 'Patients',
    actionLabel: 'Next Patient →',
    archetype: 'medical',
  },
  hospital: {
    gradient: 'from-sky-500 to-blue-700',
    bgGradient: 'from-sky-900/40 via-background to-background',
    accent: 'text-sky-400',
    accentColor: '#38BDF8',
    accentLight: 'border-sky-500/30 bg-sky-500/10',
    btnBg: 'bg-sky-600',
    btnText: 'text-white',
    statusOpen: 'from-sky-500/20 to-blue-500/10 border-sky-500/30',
    greeting: '🏥 Hospital Dashboard',
    ownerTitle: 'Administrator',
    dashTitle: 'Hospital Control',
    queueLabel: 'OPD Queue',
    actionLabel: 'Next Patient →',
    archetype: 'medical',
  },
  restaurant: {
    gradient: 'from-red-500 to-orange-600',
    bgGradient: 'from-red-900/40 via-background to-background',
    accent: 'text-red-400',
    accentColor: '#F87171',
    accentLight: 'border-red-500/30 bg-red-500/10',
    btnBg: 'bg-red-600',
    btnText: 'text-white',
    statusOpen: 'from-red-500/20 to-orange-500/10 border-red-500/30',
    greeting: '🍽️ Namaste, Chef!',
    ownerTitle: 'Chef',
    dashTitle: 'Kitchen & Floor',
    queueLabel: 'Reservations',
    actionLabel: 'Seat Next →',
    archetype: 'food',
  },
  cafe: {
    gradient: 'from-amber-500 to-yellow-600',
    bgGradient: 'from-amber-900/40 via-background to-background',
    accent: 'text-amber-400',
    accentColor: '#FBBF24',
    accentLight: 'border-amber-500/30 bg-amber-500/10',
    btnBg: 'bg-amber-600',
    btnText: 'text-white',
    statusOpen: 'from-amber-500/20 to-yellow-500/10 border-amber-500/30',
    greeting: '☕ Welcome, Barista!',
    ownerTitle: 'Barista',
    dashTitle: 'Cafe Dashboard',
    queueLabel: 'Tables',
    actionLabel: 'Seat Guest →',
    archetype: 'food',
  },
  gym: {
    gradient: 'from-red-600 to-rose-700',
    bgGradient: 'from-red-900/40 via-background to-background',
    accent: 'text-red-500',
    accentColor: '#EF4444',
    accentLight: 'border-red-500/30 bg-red-500/10',
    btnBg: 'bg-red-600',
    btnText: 'text-white',
    statusOpen: 'from-red-500/20 to-rose-500/10 border-red-500/30',
    greeting: '💪 Let\'s Crush It!',
    ownerTitle: 'Trainer',
    dashTitle: 'Gym Command',
    queueLabel: 'Members Today',
    actionLabel: 'Next Session →',
    archetype: 'professional',
  },
  spa: {
    gradient: 'from-purple-500 to-pink-600',
    bgGradient: 'from-purple-900/40 via-background to-background',
    accent: 'text-purple-400',
    accentColor: '#C084FC',
    accentLight: 'border-purple-500/30 bg-purple-500/10',
    btnBg: 'bg-purple-600',
    btnText: 'text-white',
    statusOpen: 'from-purple-500/20 to-pink-500/10 border-purple-500/30',
    greeting: '🧖 Welcome, Therapist!',
    ownerTitle: 'Therapist',
    dashTitle: 'Wellness Center',
    queueLabel: 'Appointments',
    actionLabel: 'Next Session →',
    archetype: 'beauty',
  },
  coaching: {
    gradient: 'from-indigo-500 to-blue-600',
    bgGradient: 'from-indigo-900/40 via-background to-background',
    accent: 'text-indigo-400',
    accentColor: '#818CF8',
    accentLight: 'border-indigo-500/30 bg-indigo-500/10',
    btnBg: 'bg-indigo-600',
    btnText: 'text-white',
    statusOpen: 'from-indigo-500/20 to-blue-500/10 border-indigo-500/30',
    greeting: '📚 Welcome, Teacher!',
    ownerTitle: 'Tutor',
    dashTitle: 'Coaching Center',
    queueLabel: 'Students Today',
    actionLabel: 'Start Class →',
    archetype: 'professional',
  },
  pet_care: {
    gradient: 'from-lime-500 to-green-600',
    bgGradient: 'from-lime-900/40 via-background to-background',
    accent: 'text-lime-400',
    accentColor: '#A3E635',
    accentLight: 'border-lime-500/30 bg-lime-500/10',
    btnBg: 'bg-lime-600',
    btnText: 'text-white',
    statusOpen: 'from-lime-500/20 to-green-500/10 border-lime-500/30',
    greeting: '🐾 Hello, Doc!',
    ownerTitle: 'Vet',
    dashTitle: 'Pet Clinic',
    queueLabel: 'Pets Today',
    actionLabel: 'Next Pet →',
    archetype: 'medical',
  },
  law_firm: {
    gradient: 'from-slate-500 to-gray-700',
    bgGradient: 'from-slate-900/40 via-background to-background',
    accent: 'text-slate-300',
    accentColor: '#CBD5E1',
    accentLight: 'border-slate-500/30 bg-slate-500/10',
    btnBg: 'bg-slate-600',
    btnText: 'text-white',
    statusOpen: 'from-slate-500/20 to-gray-500/10 border-slate-500/30',
    greeting: '⚖️ Good Day, Advocate!',
    ownerTitle: 'Advocate',
    dashTitle: 'Law Office',
    queueLabel: 'Consultations',
    actionLabel: 'Next Client →',
    archetype: 'professional',
  },
  photography: {
    gradient: 'from-fuchsia-500 to-pink-600',
    bgGradient: 'from-fuchsia-900/40 via-background to-background',
    accent: 'text-fuchsia-400',
    accentColor: '#E879F9',
    accentLight: 'border-fuchsia-500/30 bg-fuchsia-500/10',
    btnBg: 'bg-fuchsia-600',
    btnText: 'text-white',
    statusOpen: 'from-fuchsia-500/20 to-pink-500/10 border-fuchsia-500/30',
    greeting: '📸 Ready to Shoot!',
    ownerTitle: 'Photographer',
    dashTitle: 'Studio Hub',
    queueLabel: 'Bookings',
    actionLabel: 'Next Shoot →',
    archetype: 'professional',
  },
  repair_shop: {
    gradient: 'from-orange-500 to-amber-600',
    bgGradient: 'from-orange-900/40 via-background to-background',
    accent: 'text-orange-400',
    accentColor: '#FB923C',
    accentLight: 'border-orange-500/30 bg-orange-500/10',
    btnBg: 'bg-orange-600',
    btnText: 'text-white',
    statusOpen: 'from-orange-500/20 to-amber-500/10 border-orange-500/30',
    greeting: '🔧 Let\'s Fix Things!',
    ownerTitle: 'Technician',
    dashTitle: 'Repair Center',
    queueLabel: 'Job Queue',
    actionLabel: 'Next Job →',
    archetype: 'professional',
  },
  laundry: {
    gradient: 'from-cyan-500 to-sky-600',
    bgGradient: 'from-cyan-900/40 via-background to-background',
    accent: 'text-cyan-400',
    accentColor: '#22D3EE',
    accentLight: 'border-cyan-500/30 bg-cyan-500/10',
    btnBg: 'bg-cyan-600',
    btnText: 'text-white',
    statusOpen: 'from-cyan-500/20 to-sky-500/10 border-cyan-500/30',
    greeting: '👔 Fresh & Clean!',
    ownerTitle: 'Manager',
    dashTitle: 'Laundry Hub',
    queueLabel: 'Orders',
    actionLabel: 'Next Order →',
    archetype: 'professional',
  },
  event_planner: {
    gradient: 'from-fuchsia-600 to-rose-700',
    bgGradient: 'from-fuchsia-900/40 via-background to-background',
    accent: 'text-fuchsia-400',
    accentColor: '#E879F9',
    accentLight: 'border-fuchsia-500/30 bg-fuchsia-500/10',
    btnBg: 'bg-fuchsia-600',
    btnText: 'text-white',
    statusOpen: 'from-fuchsia-500/20 to-rose-500/10 border-fuchsia-500/30',
    greeting: '🎊 Planning Perfection!',
    ownerTitle: 'Planner',
    dashTitle: 'Event Control',
    queueLabel: 'Events',
    actionLabel: 'Next Event →',
    archetype: 'professional',
  },
  other: {
    gradient: 'from-emerald-500 to-teal-600',
    bgGradient: 'from-emerald-900/40 via-background to-background',
    accent: 'text-emerald-400',
    accentColor: '#34D399',
    accentLight: 'border-emerald-500/30 bg-emerald-500/10',
    btnBg: 'bg-emerald-600',
    btnText: 'text-white',
    statusOpen: 'from-emerald-500/20 to-teal-500/10 border-emerald-500/30',
    greeting: '🏪 Welcome!',
    ownerTitle: 'Owner',
    dashTitle: 'Business Center',
    queueLabel: 'Queue',
    actionLabel: 'Next →',
    archetype: 'professional',
  },
};

export const getCategoryTheme = (cat: BusinessCategory): CategoryTheme =>
  CATEGORY_THEMES[cat] || CATEGORY_THEMES.other;
