import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface AcuSession { id:string; patientName:string; issue:string; durationMins:number; price:number; status:'waiting'|'in-progress'|'completed'; date:string; }
export default function AcupunctureClinic() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [sessions, setSessions] = useState<AcuSession[]>([]); const [saving, setSaving] = useState(false);
  const [patientName, setPatientName] = useState(''); const [issue, setIssue] = useState('Pain Management'); const [durationMins, setDurationMins] = useState('45'); const [price, setPrice] = useState('800');
  useEffect(() => { if ((businessProfile as any)?.acuSessions) setSessions((businessProfile as any).acuSessions); }, [businessProfile]);
  const saveToDb = async (r: AcuSession[]) => { if(!user) return; setSaving(true); try { await updateDoc(doc(db,'users',user.uid),{acuSessions:r}); setSessions(r); triggerHaptic('success'); } catch(e:any){alert(e.message);} setSaving(false); };
  const add = async () => { if(!patientName) return alert('Required.'); const s:AcuSession={id:Date.now().toString(),patientName:patientName.trim(),issue,durationMins:Number(durationMins)||45,price:Number(price)||0,status:'waiting',date:new Date().toISOString().split('T')[0]}; await saveToDb([s,...sessions]); setPatientName(''); };
  const nextMap:Record<string,AcuSession['status']>={waiting:'in-progress','in-progress':'completed'};
  const advance = async (id:string) => { const s=sessions.find(x=>x.id===id); if(!s||s.status==='completed') return; await saveToDb(sessions.map(x=>x.id===id?{...x,status:nextMap[s.status]}:x)); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-green-900/60 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center gap-3 border-b border-border"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-green-400">Acupuncture 🪡</h1><p className="text-[10px] text-green-200/50 font-bold uppercase tracking-widest">{sessions.filter(s=>s.status!=='completed').length} Active</p></div></div>
    <div className="p-4 space-y-5">
      <div className="p-4 rounded-3xl bg-card border border-border grid grid-cols-2 gap-3"><input value={patientName} onChange={e=>setPatientName(e.target.value)} placeholder="Patient Name *" className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-sm font-bold text-green-200"/><select value={issue} onChange={e=>setIssue(e.target.value)} className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-green-300"><option>Pain Management</option><option>Migraine Relief</option><option>Stress / Anxiety</option><option>Sciatica</option><option>Digestive Issue</option></select><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">Mins</span><input type="number" value={durationMins} onChange={e=>setDurationMins(e.target.value)} className="w-full p-3 pl-12 rounded-xl bg-background border border-border outline-none text-xs text-green-100"/></div><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={price} onChange={e=>setPrice(e.target.value)} className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-xs font-black text-green-200"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-green-600 text-green-950 rounded-xl font-black text-xs uppercase">{saving?'...':'Add Session'}</button></div>
      <div className="space-y-2">{sessions.map(s=>(<div key={s.id} className={`p-3 rounded-2xl bg-card border border-border ${s.status==='completed'?'opacity-40':''}`}><div className="flex justify-between mb-1"><div><p className="text-xs font-black text-green-100">🪡 {s.patientName}</p><p className="text-[9px] text-text-dim">{s.issue} • {s.durationMins} mins • ₹{s.price}</p></div><span className="text-[8px] font-black text-green-400 uppercase">{s.status.replace('-',' ')}</span></div>{s.status!=='completed'&&<button onClick={()=>advance(s.id)} className="w-full py-1 mt-1 rounded-xl bg-green-500/10 text-green-400 text-[9px] font-black uppercase">→ {nextMap[s.status]}</button>}</div>))}</div>
    </div></div>);
}
