import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface AyurVisit { id:string; patientName:string; phone:string; condition:string; treatment:string; herbs:string; fee:number; date:string; followUp:string; }
export default function AyurvedaClinic() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [visits, setVisits] = useState<AyurVisit[]>([]); const [saving, setSaving] = useState(false);
  const [patientName, setPatientName] = useState(''); const [phone, setPhone] = useState(''); const [condition, setCondition] = useState(''); const [treatment, setTreatment] = useState('Panchakarma'); const [herbs, setHerbs] = useState(''); const [fee, setFee] = useState('500');
  useEffect(() => { if ((businessProfile as any)?.ayurVisits) setVisits((businessProfile as any).ayurVisits); }, [businessProfile]);
  const saveToDb = async (r: AyurVisit[]) => { if(!user) return; setSaving(true); try { await updateDoc(doc(db,'users',user.uid),{ayurVisits:r}); setVisits(r); triggerHaptic('success'); } catch(e:any){alert(e.message);} setSaving(false); };
  const add = async () => { if(!patientName) return alert('Required.'); const v:AyurVisit={id:Date.now().toString(),patientName:patientName.trim(),phone:phone.trim(),condition:condition.trim(),treatment,herbs:herbs.trim(),fee:Number(fee)||0,date:new Date().toISOString().split('T')[0],followUp:''}; await saveToDb([v,...visits]); setPatientName(''); setPhone(''); setCondition(''); setHerbs(''); };
  const todayRev=visits.filter(v=>v.date===new Date().toISOString().split('T')[0]).reduce((a,v)=>a+v.fee,0);
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-green-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center gap-3 border-b border-border"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-green-400">Ayurveda Clinic 🌿</h1><p className="text-[10px] text-green-200/50 font-bold uppercase tracking-widest">Today ₹{todayRev}</p></div></div>
    <div className="p-4 space-y-5">
      <div className="p-4 rounded-3xl bg-card border border-border grid grid-cols-2 gap-3"><input value={patientName} onChange={e=>setPatientName(e.target.value)} placeholder="Patient *" className="p-3 rounded-xl bg-background border border-border outline-none text-sm font-bold text-green-100"/><select value={treatment} onChange={e=>setTreatment(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-green-300"><option>Panchakarma</option><option>Shirodhara</option><option>Herbs</option><option>Massage</option><option>Consultation</option></select><input value={condition} onChange={e=>setCondition(e.target.value)} placeholder="Condition" className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-green-100"/><input value={herbs} onChange={e=>setHerbs(e.target.value)} placeholder="Herbs Prescribed" className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-green-100"/><div className="relative col-span-2"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={fee} onChange={e=>setFee(e.target.value)} className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-xs font-black text-green-200"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-green-600 text-white rounded-xl font-black text-xs uppercase">{saving?'...':'Log Visit'}</button></div>
      <div className="space-y-2">{visits.map(v=>(<div key={v.id} className="flex items-center gap-3 p-3 rounded-2xl bg-card border border-border"><span className="text-lg">🌿</span><div className="flex-1"><p className="text-xs font-black text-green-50">{v.patientName} — {v.treatment}</p><p className="text-[9px] text-text-dim">{v.condition||'General'} • {v.herbs||'—'} • ₹{v.fee}</p></div></div>))}</div>
    </div></div>);
}
