import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface AyurJob { id:string; patientName:string; therapy:string; days:number; status:'consultation'|'panchakarma'|'medication'|'healed'; date:string; }
export default function AyurvedicCenter() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [leads, setLeads] = useState<AyurJob[]>([]); const [saving, setSaving] = useState(false);
  const [patientName, setPatientName] = useState('Pooja Nair'); const [therapy, setTherapy] = useState('Panchakarma (Detox)'); const [days, setDays] = useState('21');
  useEffect(() => { if ((businessProfile as any)?.ayurLeads) setLeads((businessProfile as any).ayurLeads); }, [businessProfile]);
  const saveToDb = async (r: AyurJob[]) => { if(!user) return; setSaving(true); try { await updateDoc(doc(db,'users',user.uid),{ayurLeads:r}); setLeads(r); triggerHaptic('success'); } catch(e:any){alert(e.message);} setSaving(false); };
  const add = async () => { if(!patientName) return alert('Required.'); const i:AyurJob={id:Date.now().toString(),patientName:patientName.trim(),therapy,days:Number(days)||0,status:'consultation',date:new Date().toISOString().split('T')[0]}; await saveToDb([i,...leads]); setPatientName(''); };
  const nextMap:Record<string,AyurJob['status']>={consultation:'panchakarma',panchakarma:'medication',medication:'healed'};
  const advance = async (id:string) => { const i=leads.find(x=>x.id===id); if(!i||i.status==='healed') return; await saveToDb(leads.map(x=>x.id===id?{...x,status:nextMap[i.status]}:x)); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-green-900/60 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center gap-3 border-b border-border"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-green-500">Ayurvedic Center 🌿</h1><p className="text-[10px] text-green-400/50 font-bold uppercase tracking-widest">{leads.filter(l=>l.status!=='healed').length} Active Treatments</p></div></div>
    <div className="p-4 space-y-5">
      <div className="p-4 rounded-3xl bg-card border border-border grid grid-cols-2 gap-3"><input value={patientName} onChange={e=>setPatientName(e.target.value)} placeholder="Patient Name *" className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-sm font-bold text-green-200"/><select value={therapy} onChange={e=>setTherapy(e.target.value)} className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-green-300"><option>Panchakarma (Detox)</option><option>Shirodhara (Stress/Anxiety)</option><option>Abhyanga (Massage)</option><option>General Consultation / Nadi Pariksha</option></select><div className="relative col-span-2"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">Course Days</span><input type="number" value={days} onChange={e=>setDays(e.target.value)} className="w-full p-3 pl-24 rounded-xl bg-background border border-border outline-none text-xs font-black text-green-300"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-green-700 text-green-50 rounded-xl font-black text-xs uppercase">{saving?'...':'Add Patient Case'}</button></div>
      <div className="space-y-2">{leads.map(l=>(<div key={l.id} className={`flex items-center gap-3 p-3 rounded-2xl bg-card border border-border ${l.status==='healed'?'opacity-40':''}`}><span className="text-2xl">🌿</span><div className="flex-1"><p className="text-xs font-black text-green-200">{l.patientName}</p><p className="text-[9px] text-text-dim">{l.therapy}</p><p className="text-[10px] font-bold text-green-400 mt-1">{l.days} Days Course</p></div><div className="flex flex-col items-end gap-2"><span className="text-[8px] font-black text-green-400 border border-green-900 px-1 py-0.5 rounded uppercase">{l.status}</span>{l.status!=='healed'&&<button onClick={()=>advance(l.id)} className="text-[8px] font-black px-2 py-1 rounded-lg text-emerald-400 bg-emerald-500/10">Next Stage →</button>}</div></div>))}</div>
    </div></div>);
}
