import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface BDayContact { id:string; name:string; phone:string; birthday:string; lastWished:string; notes:string; }
export default function BirthdayReminder() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [contacts, setContacts] = useState<BDayContact[]>([]); const [saving, setSaving] = useState(false);
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [birthday, setBirthday] = useState('');
  useEffect(() => { if ((businessProfile as any)?.bdayContacts) setContacts((businessProfile as any).bdayContacts); }, [businessProfile]);
  const saveToDb = async (r: BDayContact[]) => { if (!user) return; setSaving(true); try { await updateDoc(doc(db, 'users', user.uid), { bdayContacts: r }); setContacts(r); triggerHaptic('success'); } catch(e:any){ alert(e.message); } setSaving(false); };
  const add = async () => { if (!name||!birthday) return alert('Required.'); const b:BDayContact={id:Date.now().toString(),name:name.trim(),phone:phone.trim(),birthday,lastWished:'',notes:''}; await saveToDb([b,...contacts]); setName(''); setPhone(''); setBirthday(''); };
  const now=new Date(); const today=contacts.filter(c=>{const d=new Date(c.birthday);return d.getMonth()===now.getMonth()&&d.getDate()===now.getDate();});
  const upcoming=contacts.filter(c=>{const d=new Date(c.birthday);d.setFullYear(now.getFullYear());if(d<now) d.setFullYear(now.getFullYear()+1);const diff=(d.getTime()-now.getTime())/(24*60*60*1000);return diff>0&&diff<=30;}).sort((a,b)=>{const da=new Date(a.birthday),db2=new Date(b.birthday);da.setFullYear(now.getFullYear());db2.setFullYear(now.getFullYear());return da.getTime()-db2.getTime();});
  const wish = (c: BDayContact) => { const text=`*🎂 Happy Birthday, ${c.name}! 🎉*\n\nWishing you a wonderful birthday from *${businessProfile?.businessName}*! 🎁\n\n_We value you as our customer. Have an amazing day!_`; window.open(`https://wa.me/91${c.phone.replace(/\D/g,'').slice(-10)}?text=${encodeURIComponent(text)}`,'_blank'); saveToDb(contacts.map(x=>x.id===c.id?{...x,lastWished:now.toISOString()}:x)); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-pink-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center justify-between border-b border-border"><div className="flex items-center gap-3"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-pink-400">Birthday Reminders 🎂</h1><p className="text-[10px] text-pink-200/50 font-bold uppercase tracking-widest">{today.length} Today</p></div></div></div>
    <div className="p-4 space-y-6">
      <div className="p-5 rounded-3xl bg-card border border-border"><div className="grid grid-cols-2 gap-3"><input type="text" value={name} onChange={e=>setName(e.target.value)} placeholder="Name *" className="w-full p-3 rounded-xl bg-background border border-border outline-none font-bold text-sm text-pink-100"/><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="w-full p-3 rounded-xl bg-background border border-border outline-none text-xs text-pink-100"/><input type="date" value={birthday} onChange={e=>setBirthday(e.target.value)} className="col-span-2 w-full p-3 rounded-xl bg-background border border-border outline-none text-xs text-pink-100"/><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-pink-600 text-white rounded-xl font-black uppercase text-xs">{saving?'Adding...':'Add Contact'}</button></div></div>
      {today.length>0&&<div className="bg-pink-500/5 border border-pink-500/20 rounded-3xl p-4"><h3 className="text-[10px] font-black text-pink-400 uppercase mb-2">🎂 Today's Birthdays!</h3>{today.map(c=>(<div key={c.id} className="flex items-center justify-between py-2"><span className="text-sm font-black text-pink-50">🎉 {c.name}</span>{c.phone&&<button onClick={()=>wish(c)} className="text-[9px] font-black text-green-400 bg-green-500/10 px-3 py-1.5 rounded-lg">Wish on WhatsApp</button>}</div>))}</div>}
      {upcoming.length>0&&<div><h3 className="text-[10px] font-black text-amber-400 uppercase tracking-widest mb-2 px-1">Upcoming (30 days)</h3><div className="space-y-1.5">{upcoming.map(c=>(<div key={c.id} className="flex items-center gap-3 p-3 rounded-2xl bg-card border border-border"><span>🎂</span><div className="flex-1"><p className="text-xs font-bold text-pink-100">{c.name}</p><p className="text-[9px] text-text-dim">{new Date(c.birthday).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</p></div></div>))}</div></div>}
    </div></div>);
}
