import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface DailyReport { id:string; date:string; totalSales:number; totalExpenses:number; profit:number; customersServed:number; topProduct:string; notes:string; }
export default function DailyReportGenerator() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [reports, setReports] = useState<DailyReport[]>([]); const [saving, setSaving] = useState(false);
  const [totalSales, setTotalSales] = useState(''); const [totalExpenses, setTotalExpenses] = useState(''); const [customersServed, setCustomersServed] = useState(''); const [topProduct, setTopProduct] = useState(''); const [notes, setNotes] = useState('');
  useEffect(() => { if ((businessProfile as any)?.dailyReports) setReports((businessProfile as any).dailyReports); }, [businessProfile]);
  const saveToDb = async (r: DailyReport[]) => { if (!user) return; setSaving(true); try { await updateDoc(doc(db, 'users', user.uid), { dailyReports: r }); setReports(r); triggerHaptic('success'); } catch(e:any){ alert(e.message); } setSaving(false); };
  const generate = async () => { const s=Number(totalSales)||0,e=Number(totalExpenses)||0; const r:DailyReport={id:Date.now().toString(),date:new Date().toISOString(),totalSales:s,totalExpenses:e,profit:s-e,customersServed:Number(customersServed)||0,topProduct:topProduct.trim(),notes:notes.trim()}; await saveToDb([r,...reports]); setTotalSales(''); setTotalExpenses(''); setCustomersServed(''); setTopProduct(''); setNotes(''); };
  const shareReport = (r:DailyReport) => { const text=`*📊 Daily Report — ${businessProfile?.businessName}*\n📅 ${new Date(r.date).toLocaleDateString()}\n\n💰 Sales: ₹${r.totalSales}\n💸 Expenses: ₹${r.totalExpenses}\n📈 Profit: ₹${r.profit}\n👥 Customers: ${r.customersServed}\n⭐ Top: ${r.topProduct||'N/A'}\n${r.notes?`\n📝 ${r.notes}`:''}`; navigator.clipboard?.writeText(text); alert('Report copied!'); };
  const avgProfit = reports.length>0?Math.round(reports.reduce((a,r)=>a+r.profit,0)/reports.length):0;
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center justify-between border-b border-border"><div className="flex items-center gap-3"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-blue-400">Daily Reports 📊</h1><p className="text-[10px] text-blue-200/50 font-bold uppercase tracking-widest">Avg Profit: ₹{avgProfit}</p></div></div></div>
    <div className="p-4 space-y-6">
      <div className="p-5 rounded-3xl bg-card border border-border"><h2 className="font-black text-sm text-text mb-3">Generate Report</h2><div className="grid grid-cols-2 gap-3"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={totalSales} onChange={e=>setTotalSales(e.target.value)} placeholder="Sales" className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-sm font-black text-emerald-300"/></div><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={totalExpenses} onChange={e=>setTotalExpenses(e.target.value)} placeholder="Expenses" className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-sm font-black text-rose-300"/></div><input type="number" value={customersServed} onChange={e=>setCustomersServed(e.target.value)} placeholder="Customers" className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-blue-100"/><input type="text" value={topProduct} onChange={e=>setTopProduct(e.target.value)} placeholder="Top Product" className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-blue-100"/><button disabled={saving} onClick={generate} className="col-span-2 py-3 bg-blue-600 text-white rounded-xl font-black uppercase text-xs">{saving?'Generating...':'Generate Report'}</button></div></div>
      <div className="space-y-3">{reports.map(r=>(<div key={r.id} className="p-4 rounded-3xl bg-card border border-border"><div className="flex justify-between items-start mb-3"><span className="text-xs font-black text-blue-300">📅 {new Date(r.date).toLocaleDateString()}</span><button onClick={()=>shareReport(r)} className="text-[9px] font-black text-blue-400 bg-blue-500/10 px-2 py-1 rounded-lg">📋 Copy</button></div><div className="grid grid-cols-3 gap-3">{[{l:'Sales',v:`₹${r.totalSales}`,c:'text-emerald-400'},{l:'Expenses',v:`₹${r.totalExpenses}`,c:'text-rose-400'},{l:'Profit',v:`₹${r.profit}`,c:r.profit>=0?'text-emerald-400':'text-rose-400'}].map(s=>(<div key={s.l} className="text-center"><p className={`text-sm font-black ${s.c}`}>{s.v}</p><p className="text-[8px] text-text-dim font-bold uppercase">{s.l}</p></div>))}</div></div>))}</div>
    </div></div>);
}
