import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface FranchiseUnit { id:string; franchiseName:string; ownerName:string; location:string; investmentAmount:number; royaltyPercent:number; status:'active'|'suspended'; startDate:string; }
export default function FranchiseManager() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [units, setUnits] = useState<FranchiseUnit[]>([]); const [saving, setSaving] = useState(false);
  const [franchiseName, setFranchiseName] = useState(''); const [ownerName, setOwnerName] = useState(''); const [location, setLocation] = useState(''); const [investmentAmount, setInvestmentAmount] = useState(''); const [royaltyPercent, setRoyaltyPercent] = useState('5');
  useEffect(() => { if ((businessProfile as any)?.franchiseUnits) setUnits((businessProfile as any).franchiseUnits); }, [businessProfile]);
  const saveToDb = async (r: FranchiseUnit[]) => { if(!user) return; setSaving(true); try { await updateDoc(doc(db,'users',user.uid),{franchiseUnits:r}); setUnits(r); triggerHaptic('success'); } catch(e:any){alert(e.message);} setSaving(false); };
  const add = async () => { if(!franchiseName||!ownerName) return alert('Required.'); const u:FranchiseUnit={id:Date.now().toString(),franchiseName:franchiseName.trim(),ownerName:ownerName.trim(),location:location.trim(),investmentAmount:Number(investmentAmount)||0,royaltyPercent:Number(royaltyPercent)||0,status:'active',startDate:new Date().toISOString().split('T')[0]}; await saveToDb([u,...units]); setFranchiseName(''); setOwnerName(''); setLocation(''); setInvestmentAmount(''); };
  const toggle = async (id:string) => saveToDb(units.map(u=>u.id===id?{...u,status:u.status==='active'?'suspended' as const:'active' as const}:u));
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-emerald-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center gap-3 border-b border-border"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-emerald-400">Franchise 🏪</h1><p className="text-[10px] text-emerald-200/50 font-bold uppercase tracking-widest">{units.filter(u=>u.status==='active').length} Active</p></div></div>
    <div className="p-4 space-y-5">
      <div className="p-4 rounded-3xl bg-card border border-border grid grid-cols-2 gap-3"><input value={franchiseName} onChange={e=>setFranchiseName(e.target.value)} placeholder="Brand *" className="p-3 rounded-xl bg-background border border-border outline-none text-sm font-bold text-emerald-100"/><input value={ownerName} onChange={e=>setOwnerName(e.target.value)} placeholder="Owner *" className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-emerald-100"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location" className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-emerald-100"/><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={investmentAmount} onChange={e=>setInvestmentAmount(e.target.value)} className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-xs font-black text-emerald-200"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-emerald-600 text-white rounded-xl font-black text-xs uppercase">{saving?'...':'Add Unit'}</button></div>
      <div className="space-y-2">{units.map(u=>(<div key={u.id} className="flex items-center gap-3 p-3 rounded-2xl bg-card border border-border"><span className="text-lg">🏪</span><div className="flex-1"><p className="text-xs font-black text-emerald-50">{u.franchiseName}</p><p className="text-[9px] text-text-dim">{u.ownerName} • {u.location} • ₹{u.investmentAmount}</p></div><button onClick={()=>toggle(u.id)} className={`text-[8px] font-black px-2 py-1 rounded-lg ${u.status==='active'?'text-emerald-400 bg-emerald-500/10':'text-rose-400 bg-rose-500/10'}`}>{u.status}</button></div>))}</div>
    </div></div>);
}
