import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface MassageSession { id:string; clientName:string; type:string; durationMins:number; price:number; status:'waiting'|'in-session'|'completed'; date:string; }
export default function MassageTherapy() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [sessions, setSessions] = useState<MassageSession[]>([]); const [saving, setSaving] = useState(false);
  const [clientName, setClientName] = useState(''); const [type, setType] = useState('Swedish Massage'); const [durationMins, setDurationMins] = useState('60'); const [price, setPrice] = useState('1500');
  useEffect(() => { if ((businessProfile as any)?.massageSessions) setSessions((businessProfile as any).massageSessions); }, [businessProfile]);
  const saveToDb = async (r: MassageSession[]) => { if(!user) return; setSaving(true); try { await updateDoc(doc(db,'users',user.uid),{massageSessions:r}); setSessions(r); triggerHaptic('success'); } catch(e:any){alert(e.message);} setSaving(false); };
  const add = async () => { if(!clientName) return alert('Required.'); const s:MassageSession={id:Date.now().toString(),clientName:clientName.trim(),type,durationMins:Number(durationMins)||60,price:Number(price)||0,status:'waiting',date:new Date().toISOString().split('T')[0]}; await saveToDb([s,...sessions]); setClientName(''); };
  const nextMap:Record<string,MassageSession['status']>={waiting:'in-session','in-session':'completed'};
  const advance = async (id:string) => { const s=sessions.find(x=>x.id===id); if(!s||s.status==='completed') return; await saveToDb(sessions.map(x=>x.id===id?{...x,status:nextMap[s.status]}:x)); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-pink-900/40 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center gap-3 border-b border-border"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-pink-400">Massage / Spa 💆‍♀️</h1><p className="text-[10px] text-pink-200/50 font-bold uppercase tracking-widest">{sessions.filter(s=>s.status!=='completed').length} Active</p></div></div>
    <div className="p-4 space-y-5">
      <div className="p-4 rounded-3xl bg-card border border-border grid grid-cols-2 gap-3"><input value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Client Name *" className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-sm font-bold text-pink-200"/><select value={type} onChange={e=>setType(e.target.value)} className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-pink-300"><option>Swedish Massage</option><option>Deep Tissue</option><option>Ayurvedic Massage</option><option>Head & Shoulder</option><option>Foot Reflexology</option></select><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">Mins</span><input type="number" value={durationMins} onChange={e=>setDurationMins(e.target.value)} className="w-full p-3 pl-12 rounded-xl bg-background border border-border outline-none text-xs text-pink-100"/></div><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={price} onChange={e=>setPrice(e.target.value)} className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-xs font-black text-pink-200"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-pink-600 text-white rounded-xl font-black text-xs uppercase">{saving?'...':'Add Session'}</button></div>
      <div className="space-y-2">{sessions.map(s=>(<div key={s.id} className={`p-3 rounded-2xl bg-card border border-border ${s.status==='completed'?'opacity-40':''}`}><div className="flex justify-between mb-1"><div><p className="text-xs font-black text-pink-100">💆‍♀️ {s.clientName}</p><p className="text-[9px] text-text-dim">{s.type} • {s.durationMins} mins • ₹{s.price}</p></div><span className="text-[8px] font-black text-pink-400 uppercase">{s.status.replace('-',' ')}</span></div>{s.status!=='completed'&&<button onClick={()=>advance(s.id)} className="w-full py-1 mt-1 rounded-xl bg-pink-500/10 text-pink-400 text-[9px] font-black uppercase">→ {nextMap[s.status]}</button>}</div>))}</div>
    </div></div>);
}
