import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface MehndiOrder { id:string; clientName:string; phone:string; occasion:string; designType:string; eventDate:string; charge:number; status:'booked'|'completed'; }
export default function MehndiArtist() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [orders, setOrders] = useState<MehndiOrder[]>([]); const [saving, setSaving] = useState(false);
  const [clientName, setClientName] = useState(''); const [phone, setPhone] = useState(''); const [occasion, setOccasion] = useState('Wedding'); const [designType, setDesignType] = useState('Bridal'); const [eventDate, setEventDate] = useState(''); const [charge, setCharge] = useState('2000');
  useEffect(() => { if ((businessProfile as any)?.mehndiOrders) setOrders((businessProfile as any).mehndiOrders); }, [businessProfile]);
  const saveToDb = async (r: MehndiOrder[]) => { if (!user) return; setSaving(true); try { await updateDoc(doc(db, 'users', user.uid), { mehndiOrders: r }); setOrders(r); triggerHaptic('success'); } catch(e:any){ alert(e.message); } setSaving(false); };
  const add = async () => { if (!clientName) return alert('Required.'); const o:MehndiOrder={id:Date.now().toString(),clientName:clientName.trim(),phone:phone.trim(),occasion,designType,eventDate,charge:Number(charge)||0,status:'booked'}; await saveToDb([o,...orders]); setClientName(''); setPhone(''); setEventDate(''); };
  const complete = async (id:string) => { await saveToDb(orders.map(o=>o.id===id?{...o,status:'completed' as MehndiOrder['status']}:o)); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-rose-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center justify-between border-b border-border"><div className="flex items-center gap-3"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-rose-400">Mehndi Artist ✋</h1><p className="text-[10px] text-rose-200/50 font-bold uppercase tracking-widest">{orders.filter(o=>o.status==='booked').length} Upcoming</p></div></div></div>
    <div className="p-4 space-y-6">
      <div className="p-5 rounded-3xl bg-card border border-border"><div className="grid grid-cols-2 gap-3"><input type="text" value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Client *" className="w-full p-3 rounded-xl bg-background border border-border outline-none font-bold text-sm text-rose-100"/><select value={occasion} onChange={e=>setOccasion(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-rose-300"><option>Wedding</option><option>Engagement</option><option>Karwa Chauth</option><option>Birthday</option><option>Festival</option></select><select value={designType} onChange={e=>setDesignType(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-rose-300"><option>Bridal</option><option>Arabic</option><option>Indian</option><option>Simple</option><option>Glitter</option></select><input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-rose-100"/><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-rose-600 text-white rounded-xl font-black uppercase text-xs">{saving?'Adding...':'Book Appointment'}</button></div></div>
      <div className="space-y-2">{orders.map(o=>(<div key={o.id} className={`flex items-center gap-3 p-3.5 rounded-2xl bg-card border border-border ${o.status==='completed'?'opacity-40':''}`}><span className="text-lg">✋</span><div className="flex-1"><p className="text-xs font-black text-rose-50">{o.clientName}</p><p className="text-[9px] text-text-dim">{o.designType} • {o.occasion}{o.eventDate&&` • ${new Date(o.eventDate).toLocaleDateString()}`}</p></div><p className="font-black text-rose-400 text-xs">₹{o.charge}</p>{o.status==='booked'&&<button onClick={()=>complete(o.id)} className="text-[8px] font-black text-emerald-400 bg-emerald-500/10 px-1.5 py-1 rounded">✓</button>}</div>))}</div>
    </div></div>);
}
