import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface Member { id:string; name:string; phone:string; memberId:string; tier:'bronze'|'silver'|'gold'|'platinum'; points:number; totalSpend:number; joinDate:string; expiryDate:string; }
export default function MembershipCard() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [members, setMembers] = useState<Member[]>([]); const [saving, setSaving] = useState(false);
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [tier, setTier] = useState<Member['tier']>('bronze');
  useEffect(() => { if ((businessProfile as any)?.members) setMembers((businessProfile as any).members); }, [businessProfile]);
  const saveToDb = async (r: Member[]) => { if (!user) return; setSaving(true); try { await updateDoc(doc(db, 'users', user.uid), { members: r }); setMembers(r); triggerHaptic('success'); } catch(e:any){ alert(e.message); } setSaving(false); };
  const add = async () => { if (!name) return alert('Required.'); const m:Member={id:Date.now().toString(),name:name.trim(),phone:phone.trim(),memberId:'MEM-'+Date.now().toString().slice(-6),tier,points:0,totalSpend:0,joinDate:new Date().toISOString(),expiryDate:new Date(Date.now()+365*24*60*60*1000).toISOString()}; await saveToDb([m,...members]); setName(''); setPhone(''); };
  const addPoints = async (id:string) => { const pts=Number(prompt('Points to add:')); if(!pts) return; await saveToDb(members.map(m=>m.id===id?{...m,points:m.points+pts}:m)); };
  const tierColors:Record<string,string>={bronze:'text-orange-400',silver:'text-zinc-300',gold:'text-yellow-400',platinum:'text-purple-300'};
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-yellow-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center justify-between border-b border-border"><div className="flex items-center gap-3"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-yellow-400">Membership 💳</h1><p className="text-[10px] text-yellow-200/50 font-bold uppercase tracking-widest">{members.length} Members</p></div></div></div>
    <div className="p-4 space-y-6">
      <div className="p-5 rounded-3xl bg-card border border-border"><div className="grid grid-cols-2 gap-3"><input type="text" value={name} onChange={e=>setName(e.target.value)} placeholder="Name *" className="w-full p-3 rounded-xl bg-background border border-border outline-none font-bold text-sm text-yellow-100"/><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="w-full p-3 rounded-xl bg-background border border-border outline-none text-xs text-yellow-100"/><select value={tier} onChange={e=>setTier(e.target.value as Member['tier'])} className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-yellow-300"><option value="bronze">🥉 Bronze</option><option value="silver">🥈 Silver</option><option value="gold">🥇 Gold</option><option value="platinum">💎 Platinum</option></select><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-yellow-600 text-yellow-950 rounded-xl font-black uppercase text-xs">{saving?'Adding...':'Issue Card'}</button></div></div>
      <div className="space-y-2">{members.map(m=>(<div key={m.id} className="p-4 rounded-2xl bg-card border border-border"><div className="flex justify-between items-start mb-1"><div><p className="text-xs font-black text-yellow-50">{m.name}</p><p className="text-[9px] text-text-dim">{m.memberId} • {new Date(m.joinDate).toLocaleDateString()}</p></div><span className={`text-sm font-black uppercase ${tierColors[m.tier]}`}>{m.tier}</span></div><div className="flex items-center justify-between mt-2"><span className="text-[10px] font-bold text-yellow-300">⭐ {m.points} pts</span><button onClick={()=>addPoints(m.id)} className="text-[9px] font-black text-emerald-400 bg-emerald-500/10 px-2 py-1 rounded-lg">+ Points</button></div></div>))}</div>
    </div></div>);
}
