import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface Referral { id:string; referrerName:string; referrerPhone:string; referredName:string; referredPhone:string; status:'pending'|'converted'|'rewarded'; reward:number; date:string; }
export default function ReferralProgram() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [referrals, setReferrals] = useState<Referral[]>([]); const [saving, setSaving] = useState(false);
  const [referrerName, setReferrerName] = useState(''); const [referredName, setReferredName] = useState(''); const [referredPhone, setReferredPhone] = useState(''); const [reward, setReward] = useState('100');
  useEffect(() => { if ((businessProfile as any)?.referrals) setReferrals((businessProfile as any).referrals); }, [businessProfile]);
  const saveToDb = async (r: Referral[]) => { if (!user) return; setSaving(true); try { await updateDoc(doc(db, 'users', user.uid), { referrals: r }); setReferrals(r); triggerHaptic('success'); } catch(e:any){ alert(e.message); } setSaving(false); };
  const add = async () => { if (!referrerName||!referredName) return alert('Required.'); const r:Referral={id:Date.now().toString(),referrerName:referrerName.trim(),referrerPhone:'',referredName:referredName.trim(),referredPhone:referredPhone.trim(),status:'pending',reward:Number(reward)||100,date:new Date().toISOString()}; await saveToDb([r,...referrals]); setReferrerName(''); setReferredName(''); setReferredPhone(''); };
  const updateStatus = async (id:string,s:Referral['status']) => { await saveToDb(referrals.map(r=>r.id===id?{...r,status:s}:r)); };
  const converted=referrals.filter(r=>r.status==='converted'||r.status==='rewarded').length; const totalRewards=referrals.filter(r=>r.status==='rewarded').reduce((a,r)=>a+r.reward,0);
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-rose-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center justify-between border-b border-border"><div className="flex items-center gap-3"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-rose-400">Referrals 🤝</h1><p className="text-[10px] text-rose-200/50 font-bold uppercase tracking-widest">{converted} Converted • ₹{totalRewards} Rewarded</p></div></div></div>
    <div className="p-4 space-y-6">
      <div className="p-5 rounded-3xl bg-card border border-border"><div className="grid grid-cols-2 gap-3"><input type="text" value={referrerName} onChange={e=>setReferrerName(e.target.value)} placeholder="Referred By *" className="w-full p-3 rounded-xl bg-background border border-border outline-none font-bold text-sm text-rose-100"/><input type="text" value={referredName} onChange={e=>setReferredName(e.target.value)} placeholder="New Customer *" className="w-full p-3 rounded-xl bg-background border border-border outline-none text-xs text-rose-100"/><input type="tel" value={referredPhone} onChange={e=>setReferredPhone(e.target.value)} placeholder="New Customer Phone" className="w-full p-3 rounded-xl bg-background border border-border outline-none text-xs text-rose-100"/><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={reward} onChange={e=>setReward(e.target.value)} className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-xs font-black text-rose-200"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-rose-600 text-white rounded-xl font-black uppercase text-xs">{saving?'Adding...':'Add Referral'}</button></div></div>
      <div className="space-y-2">{referrals.map(r=>(<div key={r.id} className="p-3.5 rounded-2xl bg-card border border-border"><div className="flex justify-between items-start mb-2"><div><p className="text-xs font-black text-rose-50">{r.referredName}</p><p className="text-[9px] text-text-dim">By: {r.referrerName} • ₹{r.reward} reward</p></div><span className={`text-[8px] font-black uppercase px-1.5 py-0.5 rounded ${r.status==='rewarded'?'bg-emerald-500/20 text-emerald-400':r.status==='converted'?'bg-blue-500/20 text-blue-400':'bg-amber-500/20 text-amber-400'}`}>{r.status}</span></div>
        <div className="flex gap-1">{r.status==='pending'&&<button onClick={()=>updateStatus(r.id,'converted')} className="flex-1 py-1.5 rounded-lg bg-blue-500/10 text-blue-400 text-[9px] font-black uppercase">Convert</button>}{r.status==='converted'&&<button onClick={()=>updateStatus(r.id,'rewarded')} className="flex-1 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-400 text-[9px] font-black uppercase">Mark Rewarded</button>}</div></div>))}</div>
    </div></div>);
}
