import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface CatProduct { id:string; name:string; brand:string; category:string; mrp:number; sellingPrice:number; commission:number; inStock:boolean; }
export default function SalonProductCatalog() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [products, setProducts] = useState<CatProduct[]>([]); const [saving, setSaving] = useState(false);
  const [name, setName] = useState(''); const [brand, setBrand] = useState(''); const [category, setCategory] = useState('Hair Care'); const [mrp, setMrp] = useState(''); const [sellingPrice, setSellingPrice] = useState('');
  useEffect(() => { if ((businessProfile as any)?.salonProducts) setProducts((businessProfile as any).salonProducts); }, [businessProfile]);
  const saveToDb = async (r: CatProduct[]) => { if (!user) return; setSaving(true); try { await updateDoc(doc(db, 'users', user.uid), { salonProducts: r }); setProducts(r); triggerHaptic('success'); } catch(e:any){ alert(e.message); } setSaving(false); };
  const add = async () => { if (!name) return alert('Required.'); const m=Number(mrp)||0,s=Number(sellingPrice)||m; const p:CatProduct={id:Date.now().toString(),name:name.trim(),brand:brand.trim(),category,mrp:m,sellingPrice:s,commission:s-m,inStock:true}; await saveToDb([p,...products]); setName(''); setBrand(''); setMrp(''); setSellingPrice(''); };
  const toggle = async (id:string) => { await saveToDb(products.map(p=>p.id===id?{...p,inStock:!p.inStock}:p)); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-rose-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center justify-between border-b border-border"><div className="flex items-center gap-3"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-rose-400">Product Catalog 🧴</h1><p className="text-[10px] text-rose-200/50 font-bold uppercase tracking-widest">{products.filter(p=>p.inStock).length} In Stock</p></div></div></div>
    <div className="p-4 space-y-6">
      <div className="p-5 rounded-3xl bg-card border border-border"><div className="grid grid-cols-2 gap-3"><input type="text" value={name} onChange={e=>setName(e.target.value)} placeholder="Product *" className="w-full p-3 rounded-xl bg-background border border-border outline-none font-bold text-sm text-rose-100"/><input type="text" value={brand} onChange={e=>setBrand(e.target.value)} placeholder="Brand" className="w-full p-3 rounded-xl bg-background border border-border outline-none text-xs text-rose-100"/><select value={category} onChange={e=>setCategory(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-rose-300"><option>Hair Care</option><option>Skin Care</option><option>Beard</option><option>Styling</option><option>Tools</option><option>Other</option></select><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={mrp} onChange={e=>setMrp(e.target.value)} placeholder="MRP" className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-xs font-black text-rose-200"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-rose-600 text-white rounded-xl font-black uppercase text-xs">{saving?'Adding...':'Add Product'}</button></div></div>
      <div className="space-y-2">{products.map(p=>(<div key={p.id} className={`flex items-center gap-3 p-3 rounded-2xl bg-card border border-border ${!p.inStock?'opacity-30':''}`}><span className="text-lg">🧴</span><div className="flex-1"><p className="text-xs font-black text-rose-50">{p.name}</p><p className="text-[9px] text-text-dim">{p.brand&&`${p.brand} • `}{p.category}</p></div><p className="text-xs font-black text-rose-400">₹{p.mrp}</p><button onClick={()=>toggle(p.id)} className={`text-[8px] font-black px-1.5 py-0.5 rounded ${p.inStock?'bg-emerald-500/20 text-emerald-400':'bg-rose-500/20 text-rose-400'}`}>{p.inStock?'In':'Out'}</button></div>))}</div>
    </div></div>);
}
