import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface SpaBooking { id:string; clientName:string; phone:string; service:string; therapist:string; date:string; time:string; duration:number; charge:number; status:'booked'|'in_progress'|'completed'; }
export default function SpaWellness() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [bookings, setBookings] = useState<SpaBooking[]>([]); const [saving, setSaving] = useState(false);
  const [clientName, setClientName] = useState(''); const [service, setService] = useState('Swedish Massage'); const [date, setDate] = useState(''); const [time, setTime] = useState('10:00'); const [charge, setCharge] = useState('1500');
  useEffect(() => { if ((businessProfile as any)?.spaBookings) setBookings((businessProfile as any).spaBookings); }, [businessProfile]);
  const saveToDb = async (r: SpaBooking[]) => { if(!user) return; setSaving(true); try { await updateDoc(doc(db,'users',user.uid),{spaBookings:r}); setBookings(r); triggerHaptic('success'); } catch(e:any){alert(e.message);} setSaving(false); };
  const add = async () => { if(!clientName) return alert('Required.'); const b:SpaBooking={id:Date.now().toString(),clientName:clientName.trim(),phone:'',service,therapist:'',date,time,duration:60,charge:Number(charge)||0,status:'booked'}; await saveToDb([b,...bookings]); setClientName(''); setDate(''); };
  const advance = async (id:string) => { const b=bookings.find(x=>x.id===id); if(!b||b.status==='completed') return; await saveToDb(bookings.map(x=>x.id===id?{...x,status:b.status==='booked'?'in_progress':'completed' as SpaBooking['status']}:x)); };
  const todayRev=bookings.filter(b=>b.status==='completed'&&b.date===new Date().toISOString().split('T')[0]).reduce((a,b)=>a+b.charge,0);
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-rose-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center gap-3 border-b border-border"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-rose-400">Spa & Wellness 🧖</h1><p className="text-[10px] text-rose-200/50 font-bold uppercase tracking-widest">Today ₹{todayRev}</p></div></div>
    <div className="p-4 space-y-5">
      <div className="p-4 rounded-3xl bg-card border border-border grid grid-cols-2 gap-3"><input value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Client *" className="p-3 rounded-xl bg-background border border-border outline-none text-sm font-bold text-rose-100"/><select value={service} onChange={e=>setService(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-rose-300"><option>Swedish Massage</option><option>Deep Tissue</option><option>Aromatherapy</option><option>Facial</option><option>Body Wrap</option><option>Foot Spa</option></select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-rose-100"/><input type="time" value={time} onChange={e=>setTime(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs text-rose-100"/><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-rose-600 text-white rounded-xl font-black text-xs uppercase">{saving?'...':'Book Session'}</button></div>
      <div className="space-y-2">{bookings.map(b=>(<div key={b.id} className={`p-3.5 rounded-2xl bg-card border border-border ${b.status==='completed'?'opacity-40':''}`}><div className="flex justify-between items-start mb-1"><div><p className="text-xs font-black text-rose-50">{b.clientName} — {b.service}</p><p className="text-[9px] text-text-dim">{b.date} {b.time} • ₹{b.charge}</p></div><span className={`text-[8px] font-black uppercase ${b.status==='in_progress'?'text-amber-400':'text-rose-400'}`}>{b.status.replace(/_/g,' ')}</span></div>{b.status!=='completed'&&<button onClick={()=>advance(b.id)} className="w-full py-1.5 rounded-xl bg-rose-500/10 text-rose-400 text-[9px] font-black uppercase">{b.status==='booked'?'Start →':'Complete ✓'}</button>}</div>))}</div>
    </div></div>);
}
