import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface Sub { id:string; customerName:string; phone:string; plan:string; amount:number; startDate:string; endDate:string; status:'active'|'expiring'|'expired'; autoRenew:boolean; }
export default function SubscriptionManager() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [subs, setSubs] = useState<Sub[]>([]); const [saving, setSaving] = useState(false);
  const [customerName, setCustomerName] = useState(''); const [phone, setPhone] = useState(''); const [plan, setPlan] = useState('Monthly'); const [amount, setAmount] = useState('');
  useEffect(() => { if ((businessProfile as any)?.subscriptions) setSubs((businessProfile as any).subscriptions); }, [businessProfile]);
  const saveToDb = async (r: Sub[]) => { if (!user) return; setSaving(true); try { await updateDoc(doc(db, 'users', user.uid), { subscriptions: r }); setSubs(r); triggerHaptic('success'); } catch(e:any){ alert(e.message); } setSaving(false); };
  const add = async () => { if (!customerName||!amount) return alert('Required.'); const dur = plan==='Monthly'?30:plan==='Quarterly'?90:plan==='Half-Yearly'?180:365; const s:Sub={id:Date.now().toString(),customerName:customerName.trim(),phone:phone.trim(),plan,amount:Number(amount),startDate:new Date().toISOString(),endDate:new Date(Date.now()+dur*24*60*60*1000).toISOString(),status:'active',autoRenew:false}; await saveToDb([s,...subs]); setCustomerName(''); setPhone(''); setAmount(''); };
  const now=new Date(); const active=subs.filter(s=>new Date(s.endDate)>now); const expiring=subs.filter(s=>{const d=new Date(s.endDate);return d>now&&d<new Date(Date.now()+7*24*60*60*1000);}); const expired=subs.filter(s=>new Date(s.endDate)<=now); const mrr=active.reduce((a,s)=>a+s.amount,0);
  const remind = (s:Sub) => { const text=`*📋 Subscription Reminder - ${businessProfile?.businessName}*\nHi ${s.customerName},\nYour ${s.plan} subscription (₹${s.amount}) expires on ${new Date(s.endDate).toLocaleDateString()}.\n\n_Please renew to continue enjoying our services!_`; window.open(`https://wa.me/91${s.phone.replace(/\D/g,'').slice(-10)}?text=${encodeURIComponent(text)}`,'_blank'); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-purple-900/20 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center justify-between border-b border-border"><div className="flex items-center gap-3"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-purple-400">Subscriptions 🔄</h1><p className="text-[10px] text-purple-200/50 font-bold uppercase tracking-widest">{active.length} Active • ₹{mrr} MRR</p></div></div></div>
    <div className="p-4 space-y-6">
      <div className="p-5 rounded-3xl bg-card border border-border"><div className="grid grid-cols-2 gap-3">
        <input type="text" value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Customer *" className="w-full p-3 rounded-xl bg-background border border-border outline-none font-bold text-sm text-purple-100"/>
        <input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="w-full p-3 rounded-xl bg-background border border-border outline-none text-xs text-purple-100"/>
        <select value={plan} onChange={e=>setPlan(e.target.value)} className="w-full p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-purple-300"><option>Monthly</option><option>Quarterly</option><option>Half-Yearly</option><option>Yearly</option></select>
        <div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">₹</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount *" className="w-full p-3 pl-7 rounded-xl bg-background border border-border outline-none text-xs font-black text-purple-200"/></div>
        <button disabled={saving} onClick={add} className="col-span-2 py-3 bg-purple-600 text-white rounded-xl font-black uppercase text-xs">{saving?'Adding...':'Add Subscription'}</button>
      </div></div>
      {expiring.length>0&&<div className="bg-amber-500/5 border border-amber-500/20 rounded-2xl p-3"><p className="text-[9px] font-black text-amber-400 uppercase mb-2">⚠️ Expiring This Week ({expiring.length})</p>{expiring.map(s=>(<div key={s.id} className="flex items-center justify-between py-1"><span className="text-xs text-amber-100">{s.customerName}</span><button onClick={()=>remind(s)} className="text-[9px] font-black text-green-400 bg-green-500/10 px-2 py-1 rounded-lg">Remind</button></div>))}</div>}
      <div className="space-y-2">{subs.map(s=>{const exp=new Date(s.endDate)<now;return(<div key={s.id} className={`flex items-center gap-3 p-3.5 rounded-2xl bg-card border border-border ${exp?'opacity-40':''}`}><div className="flex-1"><p className="text-xs font-black text-purple-50">{s.customerName}</p><p className="text-[9px] text-text-dim">{s.plan} • ₹{s.amount} • Until {new Date(s.endDate).toLocaleDateString()}</p></div><span className={`text-[8px] font-black uppercase ${exp?'text-rose-400':'text-emerald-400'}`}>{exp?'Expired':'Active'}</span></div>);})}</div>
    </div></div>);
}
