import { useState, useEffect } from 'react';import { useNavigate } from 'react-router-dom';import { useApp } from '../store/AppContext';import { doc, updateDoc } from 'firebase/firestore';import { db } from '../firebase';import { triggerHaptic } from '../utils/haptics';
interface TattooJob { id:string; clientName:string; designSize:string; type:string; price:number; advance:number; status:'booked'|'designing'|'ink-session'|'done'; date:string; }
export default function TattooStudio() { const { user, businessProfile } = useApp(); const nav = useNavigate(); const [jobs, setJobs] = useState<TattooJob[]>([]); const [saving, setSaving] = useState(false);
  const [clientName, setClientName] = useState(''); const [designSize, setDesignSize] = useState('Small (under 3 inch)'); const [type, setType] = useState('Black & Grey'); const [price, setPrice] = useState('2000');
  useEffect(() => { if ((businessProfile as any)?.tattooJobs) setJobs((businessProfile as any).tattooJobs); }, [businessProfile]);
  const saveToDb = async (r: TattooJob[]) => { if(!user) return; setSaving(true); try { await updateDoc(doc(db,'users',user.uid),{tattooJobs:r}); setJobs(r); triggerHaptic('success'); } catch(e:any){alert(e.message);} setSaving(false); };
  const add = async () => { if(!clientName) return alert('Required.'); const j:TattooJob={id:Date.now().toString(),clientName:clientName.trim(),designSize,type,price:Number(price)||0,advance:0,status:'booked',date:new Date().toISOString().split('T')[0]}; await saveToDb([j,...jobs]); setClientName(''); };
  const nextMap:Record<string,TattooJob['status']>={booked:'designing',designing:'ink-session','ink-session':'done'};
  const advance = async (id:string) => { const j=jobs.find(x=>x.id===id); if(!j||j.status==='done') return; await saveToDb(jobs.map(x=>x.id===id?{...x,status:nextMap[j.status]}:x)); };
  return (<div className="min-h-screen bg-background pb-20 animate-fadeIn bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-zinc-900/80 via-background to-background">
    <div className="p-4 glass-strong sticky top-0 z-20 flex items-center gap-3 border-b border-border"><button onClick={()=>nav('/barber/dashboard')} className="w-10 h-10 flex items-center justify-center rounded-full bg-card-2">←</button><div><h1 className="font-black text-lg text-zinc-300">Tattoo Studio 🖋️</h1><p className="text-[10px] text-zinc-400/50 font-bold uppercase tracking-widest">{jobs.filter(j=>j.status!=='done').length} WIP Tattoos</p></div></div>
    <div className="p-4 space-y-5">
      <div className="p-4 rounded-3xl bg-card border border-border grid grid-cols-2 gap-3"><input value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Client Name *" className="col-span-2 p-3 rounded-xl bg-background border border-border outline-none text-sm font-bold text-zinc-200"/><select value={designSize} onChange={e=>setDesignSize(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-zinc-300"><option>Small (under 3 inch)</option><option>Medium (3-6 inch)</option><option>Large (Half Sleeve)</option><option>Full Sleeve</option><option>Custom Back</option></select><select value={type} onChange={e=>setType(e.target.value)} className="p-3 rounded-xl bg-background border border-border outline-none text-xs font-bold text-zinc-300"><option>Black & Grey</option><option>Color</option><option>Tribal</option><option>Minimalist</option><option>Coverup</option></select><div className="relative col-span-2"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim text-xs">Total ₹</span><input type="number" value={price} onChange={e=>setPrice(e.target.value)} className="w-full p-3 pl-16 rounded-xl bg-background border border-border outline-none text-xs font-black text-zinc-200"/></div><button disabled={saving} onClick={add} className="col-span-2 py-3 bg-zinc-600 text-zinc-950 rounded-xl font-black text-xs uppercase">{saving?'...':'Book Tattoo'}</button></div>
      <div className="space-y-2">{jobs.map(j=>(<div key={j.id} className={`p-3 rounded-2xl bg-card border border-border ${j.status==='done'?'opacity-40':''}`}><div className="flex justify-between mb-1"><div><p className="text-xs font-black text-zinc-100">{j.clientName}</p><p className="text-[9px] text-text-dim">{j.designSize} • {j.type} • ₹{j.price}</p></div><span className="text-[8px] font-black text-zinc-400 uppercase">{j.status.replace('-',' ')}</span></div>{j.status!=='done'&&<button onClick={()=>advance(j.id)} className="w-full py-1 mt-1 rounded-xl bg-zinc-500/10 text-zinc-400 text-[9px] font-black uppercase">→ {nextMap[j.status]}</button>}</div>))}</div>
    </div></div>);
}
